# Generated by Django 3.2.8 on 2022-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, max_length=256, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, default=0, max_length=256, verbose_name='Size'),
        ),
    ]
